# Generated by Django 2.1.7 on 2019-03-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('очередь', 'очередь'), ('в работе', 'в работе'), ('сделано', 'сделано')], default='очередь', max_length=255)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('time_planned', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
