# Generated by Django 2.1.7 on 2019-03-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190309_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='finish_date',
        ),
    ]
